/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaomi_micloud_imagetagginglib_ImageTaggingAPI */

#ifndef _Included_com_xiaomi_micloud_imagetagginglib_ImageTaggingAPI
#define _Included_com_xiaomi_micloud_imagetagginglib_ImageTaggingAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaomi_micloud_imagetagginglib_ImageTaggingAPI
 * Method:    Init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xiaomi_micloud_imagetagginglib_ImageTaggingAPI_Init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_xiaomi_micloud_imagetagginglib_ImageTaggingAPI
 * Method:    GetTags
 * Signature: ([BJLjava/util/ArrayList;)I
 */
JNIEXPORT jint JNICALL Java_com_xiaomi_micloud_imagetagginglib_ImageTaggingAPI_GetTags
  (JNIEnv *, jobject, jbyteArray, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
